require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - '.git/**/*'
    - 'caches/**/*'
  TargetRubyVersion: 2.5.1

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Naming/UncommunicativeMethodParamName:
  MinNameLength: 2

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
